const SUPER_CHAIN_PROTO_PROP = '_super',
  SUPER_CHAIN_APPLY_PROP = '_apply',
  PROTOTYPE_IS_EXTENDED_PROP = '_isExtended'

export {
  SUPER_CHAIN_PROTO_PROP,
  SUPER_CHAIN_APPLY_PROP,
  PROTOTYPE_IS_EXTENDED_PROP
}
